import assert from 'assert';
import mysql from 'mysql2/promise';
import dotenv from 'dotenv';

dotenv.config();

const BASE_URL = 'http://localhost:5001/api';

async function runTests() {
  console.log('🚀 Starting integration tests...');

  // Setup DB connection for direct validation and cleanup
  const db = await mysql.createPool({
    host: process.env.DB_HOST,
    port: process.env.DB_PORT || 3306,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME
  });

  let testProjectId = null;

  try {
    // ----------------------------------------------------
    // TEST 1: Login
    // ----------------------------------------------------
    console.log('Test 1: Verifying student and supervisor login...');
    
    // Login Student
    const studentLoginRes = await fetch(`${BASE_URL}/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username: 'alice', password: 'password123' })
    });
    assert.strictEqual(studentLoginRes.status, 200, 'Student login should succeed');
    const studentSession = await studentLoginRes.json();
    assert.ok(studentSession.token, 'Student login should return a token');
    assert.strictEqual(studentSession.role, 'student');

    // Login Supervisor
    const supervisorLoginRes = await fetch(`${BASE_URL}/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username: 'dr_john', password: 'password123' })
    });
    assert.strictEqual(supervisorLoginRes.status, 200, 'Supervisor login should succeed');
    const supervisorSession = await supervisorLoginRes.json();
    assert.ok(supervisorSession.token, 'Supervisor login should return a token');
    assert.strictEqual(supervisorSession.role, 'supervisor');

    console.log('✅ Login tests passed.');

    // ----------------------------------------------------
    // TEST 2: Permissions (Guardrails)
    // ----------------------------------------------------
    console.log('Test 2: Verifying role-based route permissions...');
    
    // Unauthenticated GET
    const unauthGetRes = await fetch(`${BASE_URL}/projects`);
    assert.strictEqual(unauthGetRes.status, 401, 'Request without token should return 401');

    // Supervisor trying to submit project (Forbidden)
    const supervisorSubmitRes = await fetch(`${BASE_URL}/projects`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${supervisorSession.token}`
      },
      body: JSON.stringify({
        title: 'Unauthorized Test',
        description: 'Should fail',
        category: 'Other',
        supervisor_name: 'Dr. John Doe'
      })
    });
    assert.strictEqual(supervisorSubmitRes.status, 403, 'Supervisors should be forbidden from submitting projects');

    console.log('✅ Permissions guardrail tests passed.');

    // ----------------------------------------------------
    // TEST 3: Saving to Local MySQL & Submitting (Student)
    // ----------------------------------------------------
    console.log('Test 3: Creating/submitting a new project...');
    
    const projectPayload = {
      title: 'Automated Test Submission',
      description: 'A mock project generated by automated test runner.',
      category: 'Cybersecurity',
      supervisor_name: 'Dr. John Doe'
    };

    const submitRes = await fetch(`${BASE_URL}/projects`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${studentSession.token}`
      },
      body: JSON.stringify(projectPayload)
    });
    assert.strictEqual(submitRes.status, 201, 'Student project submission should succeed');
    const submitResult = await submitRes.json();
    assert.ok(submitResult.id, 'Submission response should include project id');
    testProjectId = submitResult.id;

    // Direct MySQL validation
    const [dbRows] = await db.query('SELECT * FROM projects WHERE id = ?', [testProjectId]);
    assert.strictEqual(dbRows.length, 1, 'Project should exist in MySQL database');
    assert.strictEqual(dbRows[0].title, projectPayload.title);
    assert.strictEqual(dbRows[0].status, 'Pending', 'Initial status should be Pending');

    console.log('✅ Submission and MySQL save tests passed.');

    // ----------------------------------------------------
    // TEST 4: Blocked Student Edit (When status is Pending)
    // ----------------------------------------------------
    console.log('Test 4: Verifying students cannot edit a Pending project...');

    const updatePayload = {
      title: 'Attempted Malicious Update',
      description: 'An updated description that should be rejected.',
      category: 'Cybersecurity',
      supervisor_name: 'Dr. John Doe'
    };

    const studentPendingUpdateRes = await fetch(`${BASE_URL}/projects/${testProjectId}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${studentSession.token}`
      },
      body: JSON.stringify(updatePayload)
    });
    assert.strictEqual(studentPendingUpdateRes.status, 403, 'Students must be blocked from editing Pending projects');
    console.log('✅ Blocked pending edit tests passed.');

    // ----------------------------------------------------
    // TEST 5: Supervisor Requests Revision
    // ----------------------------------------------------
    console.log('Test 5: Supervisor requesting revisions on the project...');

    const reviewRevisionPayload = {
      status: 'Revision Requested',
      supervisor_feedback: 'Please update the project title and resubmit.'
    };

    const supervisorRevisionRes = await fetch(`${BASE_URL}/projects/${testProjectId}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${supervisorSession.token}`
      },
      body: JSON.stringify(reviewRevisionPayload)
    });
    assert.strictEqual(supervisorRevisionRes.status, 200, 'Supervisor revision request should succeed');

    // Verify status in DB
    const [dbRowsRevision] = await db.query('SELECT * FROM projects WHERE id = ?', [testProjectId]);
    assert.strictEqual(dbRowsRevision[0].status, 'Revision Requested');
    console.log('✅ Revision request status verified.');

    // ----------------------------------------------------
    // TEST 6: Student Edit & Resubmit (Allowed during Revision Requested)
    // ----------------------------------------------------
    console.log('Test 6: Testing student edit details and resubmit...');

    const resubmitPayload = {
      title: 'Automated Test Submission (Resubmitted)',
      description: 'A revised mock project description.',
      category: 'Cybersecurity',
      supervisor_name: 'Dr. John Doe'
    };

    const studentResubmitRes = await fetch(`${BASE_URL}/projects/${testProjectId}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${studentSession.token}`
      },
      body: JSON.stringify(resubmitPayload)
    });
    assert.strictEqual(studentResubmitRes.status, 200, 'Student details resubmit should succeed');

    // Verify in DB that details are updated and status resets back to Pending
    const [dbRowsResubmitted] = await db.query('SELECT * FROM projects WHERE id = ?', [testProjectId]);
    assert.strictEqual(dbRowsResubmitted[0].title, resubmitPayload.title);
    assert.strictEqual(dbRowsResubmitted[0].status, 'Pending', 'Resubmission should automatically reset status to Pending');
    console.log('✅ Student resubmit details and lifecycle reset verified.');

    // ----------------------------------------------------
    // TEST 7: Supervisor Final Approval
    // ----------------------------------------------------
    console.log('Test 7: Testing supervisor final approval...');

    const finalApprovalPayload = {
      status: 'Approved',
      supervisor_feedback: 'Approved after successfully resubmitting revisions.'
    };

    const supervisorApprovalRes = await fetch(`${BASE_URL}/projects/${testProjectId}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${supervisorSession.token}`
      },
      body: JSON.stringify(finalApprovalPayload)
    });
    assert.strictEqual(supervisorApprovalRes.status, 200, 'Supervisor final approval should succeed');

    // Verify in DB
    const [dbRowsApproved] = await db.query('SELECT * FROM projects WHERE id = ?', [testProjectId]);
    assert.strictEqual(dbRowsApproved[0].status, 'Approved');

    // Verify student is once again blocked from editing
    const studentBlockedFinalUpdateRes = await fetch(`${BASE_URL}/projects/${testProjectId}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${studentSession.token}`
      },
      body: JSON.stringify({ title: 'New Malicious Title' })
    });
    assert.strictEqual(studentBlockedFinalUpdateRes.status, 403, 'Students must be blocked from editing Approved projects');
    console.log('✅ Supervisor final approval and student lock verified.');

    // ----------------------------------------------------
    // TEST 8: Filtering
    // ----------------------------------------------------
    console.log('Test 8: Testing project filtering API...');

    // Filter by Status=Approved
    const filterApprovedRes = await fetch(`${BASE_URL}/projects?status=Approved`, {
      headers: { 'Authorization': `Bearer ${studentSession.token}` }
    });
    assert.strictEqual(filterApprovedRes.status, 200);
    const approvedProjects = await filterApprovedRes.json();
    assert.ok(approvedProjects.every(p => p.status === 'Approved'), 'All returned projects should be Approved');

    console.log('✅ Project filtering tests passed.');

  } catch (error) {
    console.error('❌ Integration tests failed:', error);
    process.exit(1);
  } finally {
    // ----------------------------------------------------
    // CLEANUP
    // ----------------------------------------------------
    if (testProjectId) {
      console.log('🧹 Cleaning up test data...');
      await db.query('DELETE FROM projects WHERE id = ?', [testProjectId]);
      console.log('✅ Cleanup completed.');
    }
    await db.end();
  }

  console.log('\n🎉 ALL TESTS PASSED SUCCESSFULLY! The revision workflow works perfectly.');
}

runTests();
